export const arabicCountries = [
  "السعودية",
  "الإمارات",
  "الكويت",
  "قطر",
  "البحرين",
  "عمان",
  "اليمن",
  "العراق",
  "الأردن",
  "فلسطين",
  "لبنان",
  "سوريا",
  "مصر",
  "ليبيا",
  "تونس",
  "الجزائر",
  "المغرب",
  "موريتانيا",
  "السودان",
  "الصومال",
  "جيبوتي",
  "جزر القمر",
  "تركيا",
  "إيران",
  "باكستان",
  "الهند",
  "أفغانستان",
  "بنغلاديش",
  "إندونيسيا",
  "ماليزيا",
  "سنغافورة",
  "الفلبين",
  "تايلاند",
  "فيتنام",
  "اليابان",
  "الصين",
  "كوريا الجنوبية",
  "أستراليا",
  "نيوزيلندا",
  "روسيا",
  "أوكرانيا",
  "ألمانيا",
  "فرنسا",
  "إيطاليا",
  "إسبانيا",
  "البرتغال",
  "هولندا",
  "بلجيكا",
  "سويسرا",
  "النمسا",
  "السويد",
  "النرويج",
  "الدنمارك",
  "فنلندا",
  "المملكة المتحدة",
  "أيرلندا",
  "بولندا",
  "رومانيا",
  "اليونان",
  "كندا",
  "الولايات المتحدة",
  "المكسيك",
  "البرازيل",
  "الأرجنتين",
  "تشيلي",
  "كولومبيا",
  "جنوب أفريقيا",
  "نيجيريا",
  "كينيا",
  "إثيوبيا",
  "غانا",
  "تنزانيا",
  "أوغندا",
] as const;

const englishCountries = [
  "Saudi Arabia",
  "United Arab Emirates",
  "Kuwait",
  "Qatar",
  "Bahrain",
  "Oman",
  "Yemen",
  "Iraq",
  "Jordan",
  "Palestine",
  "Lebanon",
  "Syria",
  "Egypt",
  "Libya",
  "Tunisia",
  "Algeria",
  "Morocco",
  "Mauritania",
  "Sudan",
  "Somalia",
  "Djibouti",
  "Comoros",
  "Turkey",
  "Iran",
  "Pakistan",
  "India",
  "Afghanistan",
  "Bangladesh",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Japan",
  "China",
  "South Korea",
  "Australia",
  "New Zealand",
  "Russia",
  "Ukraine",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Portugal",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "United Kingdom",
  "Ireland",
  "Poland",
  "Romania",
  "Greece",
  "Canada",
  "United States",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Ethiopia",
  "Ghana",
  "Tanzania",
  "Uganda",
] as const;

const countryCodes = [
  "SA", "AE", "KW", "QA", "BH", "OM", "YE", "IQ", "JO", "PS", "LB", "SY", "EG", "LY", "TN", "DZ", "MA", "MR", "SD", "SO", "DJ", "KM", "TR", "IR", "PK", "IN", "AF", "BD", "ID", "MY", "SG", "PH", "TH", "VN", "JP", "CN", "KR", "AU", "NZ", "RU", "UA", "DE", "FR", "IT", "ES", "PT", "NL", "BE", "CH", "AT", "SE", "NO", "DK", "FI", "GB", "IE", "PL", "RO", "GR", "CA", "US", "MX", "BR", "AR", "CL", "CO", "ZA", "NG", "KE", "ET", "GH", "TZ", "UG",
] as const;

function localizedCountries(language: string): readonly string[] {
  const displayNames = new Intl.DisplayNames([language], { type: "region" });
  return countryCodes.map((code, index) => displayNames.of(code) ?? (language === "ar" ? arabicCountries[index] : englishCountries[index]));
}

export const countriesByLanguage = {
  ar: localizedCountries("ar"),
  en: englishCountries,
  es: localizedCountries("es"),
  fr: localizedCountries("fr"),
  de: localizedCountries("de"),
  pt: localizedCountries("pt"),
  ja: localizedCountries("ja"),
  zh: localizedCountries("zh"),
} as const;

export const countries = countriesByLanguage.en;