import type { LanguageCode } from "@/languages";

type PageCopy = {
  forgot: { title: string; subtitle: string; email: string; send: string; sending: string; back: string; success: string; error: string };
  reset: { title: string; password: string; confirm: string; save: string; saving: string; back: string; success: string; error: string };
  support: { title: string; subtitle: string; email: string; type: string; description: string; submit: string; newRequest: string; success: string; error: string; account: string; opportunity: string; payment: string; technical: string; other: string; requests: string; replies: string; noReplies: string; response: string; pending: string; open: string; inProgress: string; resolved: string; closed: string };
  review: { title: string; description: string; pending: string; approve: string; approvePublished: string; reject: string; edit: string; save: string; cancel: string; translate: string; translating: string; translated: string; access: string; error: string };
  supportTeam: { title: string; description: string; grant: string; revoke: string; admin: string; opportunities: string; reports: string; requests: string; access: string; error: string };
  submit: { title: string; description: string; name: string; shortDescription: string; details: string; link: string; earnings: string; category: string; categoryPlaceholder: string; categoryRequired: string; countries: string; devices: string; paymentMethods: string; requirements: string; optional: string; submit: string; cancel: string; loginRequired: string; invalidUrl: string; success: string; error: string; aiTitle: string; aiBadge: string; aiPlaceholder: string; aiAnalyze: string; aiAnalyzing: string; aiMissingUrl: string; aiInvalidUrl: string; aiError: string; aiDuplicate: string; aiSuccess: string };
};

export const pageCopy = {
  ar: {
    forgot: { title: "استرجاع كلمة المرور", subtitle: "أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.", email: "البريد الإلكتروني", send: "إرسال رابط الاسترجاع", sending: "جاري الإرسال...", back: "العودة إلى تسجيل الدخول", success: "تم إرسال رابط استرجاع كلمة المرور إلى بريدك الإلكتروني.", error: "تعذر إرسال رابط الاسترجاع." },
    reset: { title: "إعادة تعيين كلمة المرور", password: "كلمة المرور الجديدة", confirm: "تأكيد كلمة المرور", save: "حفظ كلمة المرور", saving: "جاري الحفظ...", back: "العودة إلى تسجيل الدخول", success: "تم تحديث كلمة المرور بنجاح.", error: "تعذر تحديث كلمة المرور." },
    support: { title: "الدعم والمساعدة", subtitle: "أرسل مشكلتك وسيتابعها فريق الدعم.", email: "البريد الإلكتروني", type: "نوع المشكلة", description: "وصف المشكلة", submit: "إرسال طلب الدعم", newRequest: "تقديم طلب", success: "تم إرسال طلب الدعم بنجاح.", error: "تعذر إرسال الطلب.", account: "الحساب", opportunity: "الفرص", payment: "المدفوعات", technical: "مشكلة تقنية", other: "أخرى", requests: "طلباتي", replies: "طلباتي والردود", noReplies: "لا توجد طلبات دعم سابقة.", response: "رد فريق الدعم", pending: "لم يتم الرد بعد", open: "جديد", inProgress: "قيد المعالجة", resolved: "تم الحل", closed: "مغلق" },
    review: { title: "مراجعة الفرص", description: "طلبات الفرص المرسلة من المستخدمين بانتظار المراجعة.", pending: "لا توجد فرص بانتظار المراجعة.", approve: "اعتماد ونشر", approvePublished: "اعتماد التعديل", reject: "رفض", edit: "تعديل", save: "حفظ التغييرات", cancel: "إلغاء", translate: "ترجمة الفرص الحالية", translating: "جارٍ إنشاء الترجمات...", translated: "تم إنشاء الترجمات", access: "ليس لديك صلاحية لمراجعة الفرص.", error: "تعذر تنفيذ الإجراء. حاول مرة أخرى." },
    supportTeam: { title: "فريق الدعم", description: "إدارة أعضاء فريق الدعم وصلاحياتهم بشكل منفصل.", grant: "إضافة إلى الدعم", revoke: "إزالة من الدعم", admin: "مدير", opportunities: "مراجعة الفرص", reports: "إدارة البلاغات", requests: "إدارة طلبات الدعم", access: "هذه الصفحة متاحة للمدير فقط.", error: "تعذر تحديث الصلاحية." },
    submit: { title: "إضافة فرصة جديدة", description: "أرسل تفاصيل الفرصة للمراجعة قبل نشرها في المنصة.", name: "اسم الفرصة", shortDescription: "وصف مختصر", details: "تفاصيل الفرصة", link: "رابط الفرصة", earnings: "الأرباح المتوقعة", category: "التصنيف", categoryPlaceholder: "اكتب للبحث ثم اختر تصنيفًا", categoryRequired: "يرجى اختيار تصنيف من القائمة.", countries: "الدول المتاحة", devices: "الأجهزة المدعومة", paymentMethods: "طرق الدفع", requirements: "المتطلبات", optional: "اختياري، افصل العناصر بفاصلة", submit: "إرسال للمراجعة", cancel: "العودة إلى الفرص", loginRequired: "يرجى تسجيل الدخول لإضافة فرصة.", invalidUrl: "يرجى إدخال رابط صحيح يبدأ بـ http:// أو https://.", success: "تم إرسال الفرصة للمراجعة. لن تظهر في قائمة الفرص حتى يتم اعتمادها.", error: "تعذر إرسال الفرصة. حاول مرة أخرى.", aiTitle: "تحليل رابط خارجي بالذكاء الاصطناعي", aiBadge: "ذكاء اصطناعي", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "تحليل الرابط", aiAnalyzing: "جارٍ التحليل...", aiMissingUrl: "يرجى إدخال رابط خارجي أولاً.", aiInvalidUrl: "يرجى إدخال رابط صحيح يبدأ بـ http أو https.", aiError: "تعذر تحليل الرابط. حاول رابطًا آخر.", aiDuplicate: "هذه الفرصة موجودة مسبقًا في قائمة المراجعة أو منشورة بالفعل.", aiSuccess: "تم تحليل الرابط وإضافة البيانات إلى النموذج للمراجعة." },
  },
  en: {
    forgot: { title: "Forgot password", subtitle: "Enter your email and we will send you a link to reset your password.", email: "Email", send: "Send recovery link", sending: "Sending...", back: "Back to login", success: "A password recovery link has been sent to your email.", error: "Could not send the recovery link." },
    reset: { title: "Reset password", password: "New password", confirm: "Confirm password", save: "Save password", saving: "Saving...", back: "Back to login", success: "Password updated successfully.", error: "Could not update the password." },
    support: { title: "Support & Help", subtitle: "Send your issue and the support team will follow up.", email: "Email address", type: "Issue type", description: "Describe the issue", submit: "Send support request", newRequest: "Submit request", success: "Your support request was sent.", error: "Could not send the request.", account: "Account", opportunity: "Opportunities", payment: "Payments", technical: "Technical issue", other: "Other", requests: "My requests", replies: "My requests and replies", noReplies: "No previous support requests.", response: "Support team reply", pending: "No reply yet", open: "Open", inProgress: "In progress", resolved: "Resolved", closed: "Closed" },
    review: { title: "Opportunity review", description: "User-submitted opportunities awaiting review.", pending: "No opportunities are awaiting review.", approve: "Approve and publish", approvePublished: "Approve changes", reject: "Reject", edit: "Edit", save: "Save changes", cancel: "Cancel", translate: "Translate current opportunities", translating: "Creating translations...", translated: "Translations created", access: "You do not have access to review opportunities.", error: "Could not complete the action. Please try again." },
    supportTeam: { title: "Support team", description: "Manage support-team members and their individual permissions.", grant: "Add to support", revoke: "Remove from support", admin: "Administrator", opportunities: "Review opportunities", reports: "Manage reports", requests: "Manage support requests", access: "This page is available to administrators only.", error: "Could not update access." },
    submit: { title: "Add a new opportunity", description: "Submit the opportunity details for review before it is published on the platform.", name: "Opportunity name", shortDescription: "Short description", details: "Opportunity details", link: "Opportunity link", earnings: "Expected earnings", category: "Category", categoryPlaceholder: "Type to search, then choose a category", categoryRequired: "Choose a category from the list.", countries: "Available countries", devices: "Supported devices", paymentMethods: "Payment methods", requirements: "Requirements", optional: "Optional, separate items with commas", submit: "Submit for review", cancel: "Back to opportunities", loginRequired: "Please sign in before adding an opportunity.", invalidUrl: "Enter a valid URL starting with http:// or https://.", success: "Your opportunity was sent for review. It will not appear until it is approved.", error: "Could not submit the opportunity. Please try again.", aiTitle: "Analyze an external link with AI", aiBadge: "AI", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "Analyze link", aiAnalyzing: "Analyzing...", aiMissingUrl: "Enter an external link first.", aiInvalidUrl: "Enter a valid link starting with http or https.", aiError: "Could not analyze the link. Try another link.", aiDuplicate: "This opportunity already exists in the review queue or has already been published.", aiSuccess: "The link was analyzed and the data was added for review." },
  },
  es: {
    forgot: { title: "Recuperar contraseña", subtitle: "Introduce tu correo y te enviaremos un enlace para restablecer la contraseña.", email: "Correo electrónico", send: "Enviar enlace", sending: "Enviando...", back: "Volver al inicio de sesión", success: "Se ha enviado el enlace de recuperación.", error: "No se pudo enviar el enlace." },
    reset: { title: "Restablecer contraseña", password: "Nueva contraseña", confirm: "Confirmar contraseña", save: "Guardar contraseña", saving: "Guardando...", back: "Volver al inicio de sesión", success: "Contraseña actualizada.", error: "No se pudo actualizar la contraseña." },
    support: { title: "Soporte y ayuda", subtitle: "Envía tu problema y el equipo de soporte te ayudará.", email: "Correo electrónico", type: "Tipo de problema", description: "Describe el problema", submit: "Enviar solicitud", newRequest: "Enviar solicitud", success: "Tu solicitud fue enviada.", error: "No se pudo enviar la solicitud.", account: "Cuenta", opportunity: "Oportunidades", payment: "Pagos", technical: "Problema técnico", other: "Otro", requests: "Mis solicitudes", replies: "Mis solicitudes y respuestas", noReplies: "No hay solicitudes anteriores.", response: "Respuesta del equipo", pending: "Aún no hay respuesta", open: "Nueva", inProgress: "En proceso", resolved: "Resuelta", closed: "Cerrada" },
    review: { title: "Revisión de oportunidades", description: "Oportunidades enviadas por usuarios pendientes de revisión.", pending: "No hay oportunidades pendientes.", approve: "Aprobar y publicar", approvePublished: "Aprobar cambios", reject: "Rechazar", edit: "Editar", save: "Guardar cambios", cancel: "Cancelar", translate: "Traducir oportunidades actuales", translating: "Creando traducciones...", translated: "Traducciones creadas", access: "No tienes permiso para revisar oportunidades.", error: "No se pudo completar la acción." },
    supportTeam: { title: "Equipo de soporte", description: "Gestiona el equipo de soporte y sus permisos.", grant: "Añadir al soporte", revoke: "Quitar del soporte", admin: "Administrador", opportunities: "Revisar oportunidades", reports: "Gestionar informes", requests: "Gestionar solicitudes", access: "Solo los administradores pueden acceder.", error: "No se pudo actualizar el acceso." },
    submit: { title: "Añadir una oportunidad", description: "Envía los detalles para revisarlos antes de publicar.", name: "Nombre", shortDescription: "Descripción breve", details: "Detalles", link: "Enlace", earnings: "Ingresos esperados", category: "Categoría", categoryPlaceholder: "Escribe para buscar y elige una categoría", categoryRequired: "Elige una categoría de la lista.", countries: "Países disponibles", devices: "Dispositivos compatibles", paymentMethods: "Métodos de pago", requirements: "Requisitos", optional: "Opcional, separa los elementos con comas", submit: "Enviar para revisión", cancel: "Volver a oportunidades", loginRequired: "Inicia sesión para añadir una oportunidad.", invalidUrl: "Introduce una URL válida con http:// o https://.", success: "La oportunidad se envió para revisión.", error: "No se pudo enviar la oportunidad.", aiTitle: "Analizar un enlace externo con IA", aiBadge: "IA", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "Analizar enlace", aiAnalyzing: "Analizando...", aiMissingUrl: "Introduce primero un enlace externo.", aiInvalidUrl: "Introduce un enlace válido que empiece por http o https.", aiError: "No se pudo analizar el enlace. Prueba con otro.", aiDuplicate: "Esta oportunidad ya existe en la cola de revisión o ya está publicada.", aiSuccess: "El enlace se analizó y los datos se añadieron para revisión." },
  },
  fr: {
    forgot: { title: "Mot de passe oublié", subtitle: "Saisissez votre e-mail pour recevoir un lien de réinitialisation.", email: "E-mail", send: "Envoyer le lien", sending: "Envoi...", back: "Retour à la connexion", success: "Le lien de récupération a été envoyé.", error: "Impossible d'envoyer le lien." },
    reset: { title: "Réinitialiser le mot de passe", password: "Nouveau mot de passe", confirm: "Confirmer le mot de passe", save: "Enregistrer", saving: "Enregistrement...", back: "Retour à la connexion", success: "Mot de passe mis à jour.", error: "Impossible de mettre à jour le mot de passe." },
    support: { title: "Support et aide", subtitle: "Envoyez votre problème, notre équipe vous répondra.", email: "E-mail", type: "Type de problème", description: "Décrivez le problème", submit: "Envoyer la demande", newRequest: "Soumettre une demande", success: "Votre demande a été envoyée.", error: "Impossible d'envoyer la demande.", account: "Compte", opportunity: "Opportunités", payment: "Paiements", technical: "Problème technique", other: "Autre", requests: "Mes demandes", replies: "Mes demandes et réponses", noReplies: "Aucune demande précédente.", response: "Réponse de l'équipe", pending: "Pas encore de réponse", open: "Nouvelle", inProgress: "En cours", resolved: "Résolue", closed: "Fermée" },
    review: { title: "Revue des opportunités", description: "Opportunités envoyées par les utilisateurs en attente de revue.", pending: "Aucune opportunité en attente.", approve: "Approuver et publier", approvePublished: "Approuver les modifications", reject: "Refuser", edit: "Modifier", save: "Enregistrer les modifications", cancel: "Annuler", translate: "Traduire les opportunités actuelles", translating: "Création des traductions...", translated: "Traductions créées", access: "Vous n'avez pas accès à la revue.", error: "Action impossible." },
    supportTeam: { title: "Équipe support", description: "Gérez l'équipe support et ses permissions.", grant: "Ajouter au support", revoke: "Retirer du support", admin: "Administrateur", opportunities: "Revoir les opportunités", reports: "Gérer les signalements", requests: "Gérer les demandes", access: "Accès réservé aux administrateurs.", error: "Impossible de mettre à jour l'accès." },
    submit: { title: "Ajouter une opportunité", description: "Envoyez les détails pour revue avant publication.", name: "Nom", shortDescription: "Description courte", details: "Détails", link: "Lien", earnings: "Revenus prévus", category: "Catégorie", categoryPlaceholder: "Écrivez pour rechercher puis choisissez une catégorie", categoryRequired: "Choisissez une catégorie dans la liste.", countries: "Pays disponibles", devices: "Appareils compatibles", paymentMethods: "Modes de paiement", requirements: "Conditions", optional: "Facultatif, séparez par des virgules", submit: "Envoyer pour revue", cancel: "Retour aux opportunités", loginRequired: "Connectez-vous pour ajouter une opportunité.", invalidUrl: "Saisissez une URL valide en http:// ou https://.", success: "L'opportunité a été envoyée pour revue.", error: "Impossible d'envoyer l'opportunité.", aiTitle: "Analyser un lien externe avec l'IA", aiBadge: "IA", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "Analyser le lien", aiAnalyzing: "Analyse en cours...", aiMissingUrl: "Saisissez d'abord un lien externe.", aiInvalidUrl: "Saisissez un lien valide commençant par http ou https.", aiError: "Impossible d'analyser le lien. Essayez-en un autre.", aiDuplicate: "Cette opportunité existe déjà dans la file de revue ou est déjà publiée.", aiSuccess: "Le lien a été analysé et les données ont été ajoutées pour revue." },
  },
  de: {
    forgot: { title: "Passwort vergessen", subtitle: "Geben Sie Ihre E-Mail ein, um einen Link zurückzusetzen.", email: "E-Mail", send: "Link senden", sending: "Wird gesendet...", back: "Zur Anmeldung", success: "Der Wiederherstellungslink wurde gesendet.", error: "Der Link konnte nicht gesendet werden." },
    reset: { title: "Passwort zurücksetzen", password: "Neues Passwort", confirm: "Passwort bestätigen", save: "Passwort speichern", saving: "Wird gespeichert...", back: "Zur Anmeldung", success: "Passwort erfolgreich aktualisiert.", error: "Passwort konnte nicht aktualisiert werden." },
    support: { title: "Support & Hilfe", subtitle: "Senden Sie Ihr Anliegen, das Support-Team hilft Ihnen.", email: "E-Mail", type: "Problemtyp", description: "Problem beschreiben", submit: "Anfrage senden", newRequest: "Anfrage einreichen", success: "Ihre Anfrage wurde gesendet.", error: "Anfrage konnte nicht gesendet werden.", account: "Konto", opportunity: "Chancen", payment: "Zahlungen", technical: "Technisches Problem", other: "Sonstiges", requests: "Meine Anfragen", replies: "Meine Anfragen und Antworten", noReplies: "Keine früheren Anfragen.", response: "Antwort des Support-Teams", pending: "Noch keine Antwort", open: "Neu", inProgress: "In Bearbeitung", resolved: "Gelöst", closed: "Geschlossen" },
    review: { title: "Chancen prüfen", description: "Von Nutzern eingereichte Chancen warten auf Prüfung.", pending: "Keine Chancen zur Prüfung.", approve: "Genehmigen und veröffentlichen", approvePublished: "Änderungen genehmigen", reject: "Ablehnen", edit: "Bearbeiten", save: "Änderungen speichern", cancel: "Abbrechen", translate: "Aktuelle Chancen übersetzen", translating: "Übersetzungen werden erstellt...", translated: "Übersetzungen erstellt", access: "Sie haben keinen Zugriff.", error: "Aktion konnte nicht abgeschlossen werden." },
    supportTeam: { title: "Support-Team", description: "Support-Mitglieder und Berechtigungen verwalten.", grant: "Zum Support hinzufügen", revoke: "Aus Support entfernen", admin: "Administrator", opportunities: "Chancen prüfen", reports: "Meldungen verwalten", requests: "Supportanfragen verwalten", access: "Nur Administratoren haben Zugriff.", error: "Zugriff konnte nicht aktualisiert werden." },
    submit: { title: "Chance hinzufügen", description: "Senden Sie die Details zur Prüfung vor der Veröffentlichung.", name: "Name", shortDescription: "Kurzbeschreibung", details: "Details", link: "Link", earnings: "Erwartete Einnahmen", category: "Kategorie", categoryPlaceholder: "Zum Suchen schreiben und eine Kategorie auswählen", categoryRequired: "Wählen Sie eine Kategorie aus der Liste.", countries: "Verfügbare Länder", devices: "Unterstützte Geräte", paymentMethods: "Zahlungsmethoden", requirements: "Voraussetzungen", optional: "Optional, durch Kommas trennen", submit: "Zur Prüfung senden", cancel: "Zurück zu den Chancen", loginRequired: "Melden Sie sich an, um eine Chance hinzuzufügen.", invalidUrl: "Geben Sie eine gültige URL mit http:// oder https:// ein.", success: "Die Chance wurde zur Prüfung gesendet.", error: "Die Chance konnte nicht gesendet werden.", aiTitle: "Externen Link mit KI analysieren", aiBadge: "KI", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "Link analysieren", aiAnalyzing: "Wird analysiert...", aiMissingUrl: "Geben Sie zuerst einen externen Link ein.", aiInvalidUrl: "Geben Sie einen gültigen Link mit http oder https ein.", aiError: "Der Link konnte nicht analysiert werden. Versuchen Sie einen anderen.", aiDuplicate: "Diese Chance ist bereits in der Prüfwarteschlange oder veröffentlicht.", aiSuccess: "Der Link wurde analysiert und die Daten zur Prüfung eingefügt." },
  },
  pt: {
    forgot: { title: "Esqueci a senha", subtitle: "Informe seu e-mail para receber um link de redefinição.", email: "E-mail", send: "Enviar link", sending: "Enviando...", back: "Voltar ao login", success: "O link de recuperação foi enviado.", error: "Não foi possível enviar o link." },
    reset: { title: "Redefinir senha", password: "Nova senha", confirm: "Confirmar senha", save: "Salvar senha", saving: "Salvando...", back: "Voltar ao login", success: "Senha atualizada.", error: "Não foi possível atualizar a senha." },
    support: { title: "Suporte e ajuda", subtitle: "Envie seu problema e nossa equipe ajudará.", email: "E-mail", type: "Tipo de problema", description: "Descreva o problema", submit: "Enviar solicitação", newRequest: "Enviar solicitação", success: "Sua solicitação foi enviada.", error: "Não foi possível enviar a solicitação.", account: "Conta", opportunity: "Oportunidades", payment: "Pagamentos", technical: "Problema técnico", other: "Outro", requests: "Minhas solicitações", replies: "Minhas solicitações e respostas", noReplies: "Nenhuma solicitação anterior.", response: "Resposta da equipe", pending: "Ainda sem resposta", open: "Nova", inProgress: "Em andamento", resolved: "Resolvida", closed: "Fechada" },
    review: { title: "Revisão de oportunidades", description: "Oportunidades enviadas por usuários aguardando revisão.", pending: "Nenhuma oportunidade aguardando revisão.", approve: "Aprovar e publicar", approvePublished: "Aprovar alterações", reject: "Rejeitar", edit: "Editar", save: "Salvar alterações", cancel: "Cancelar", translate: "Traduzir oportunidades atuais", translating: "Criando traduções...", translated: "Traduções criadas", access: "Você não tem acesso à revisão.", error: "Não foi possível concluir a ação." },
    supportTeam: { title: "Equipe de suporte", description: "Gerencie a equipe e suas permissões.", grant: "Adicionar ao suporte", revoke: "Remover do suporte", admin: "Administrador", opportunities: "Revisar oportunidades", reports: "Gerenciar denúncias", requests: "Gerenciar solicitações", access: "Acesso somente para administradores.", error: "Não foi possível atualizar o acesso." },
    submit: { title: "Adicionar oportunidade", description: "Envie os detalhes para revisão antes da publicação.", name: "Nome", shortDescription: "Descrição curta", details: "Detalhes", link: "Link", earnings: "Ganhos esperados", category: "Categoria", categoryPlaceholder: "Digite para pesquisar e escolha uma categoria", categoryRequired: "Escolha uma categoria da lista.", countries: "Países disponíveis", devices: "Dispositivos compatíveis", paymentMethods: "Métodos de pagamento", requirements: "Requisitos", optional: "Opcional, separe por vírgulas", submit: "Enviar para revisão", cancel: "Voltar às oportunidades", loginRequired: "Entre para adicionar uma oportunidade.", invalidUrl: "Informe uma URL válida com http:// ou https://.", success: "A oportunidade foi enviada para revisão.", error: "Não foi possível enviar a oportunidade.", aiTitle: "Analisar link externo com IA", aiBadge: "IA", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "Analisar link", aiAnalyzing: "Analisando...", aiMissingUrl: "Insira primeiro um link externo.", aiInvalidUrl: "Insira um link válido que comece com http ou https.", aiError: "Não foi possível analisar o link. Tente outro.", aiDuplicate: "Esta oportunidade já existe na fila de revisão ou já foi publicada.", aiSuccess: "O link foi analisado e os dados foram adicionados para revisão." },
  },
  ja: {
    forgot: { title: "パスワードを忘れた場合", subtitle: "メールアドレスを入力するとリセットリンクを送信します。", email: "メールアドレス", send: "リンクを送信", sending: "送信中...", back: "ログインに戻る", success: "リセットリンクを送信しました。", error: "リンクを送信できませんでした。" },
    reset: { title: "パスワードをリセット", password: "新しいパスワード", confirm: "パスワードを確認", save: "パスワードを保存", saving: "保存中...", back: "ログインに戻る", success: "パスワードを更新しました。", error: "パスワードを更新できませんでした。" },
    support: { title: "サポートとヘルプ", subtitle: "問題を送信するとサポートチームが対応します。", email: "メールアドレス", type: "問題の種類", description: "問題の説明", submit: "サポート依頼を送信", newRequest: "依頼を送信", success: "依頼を送信しました。", error: "依頼を送信できませんでした。", account: "アカウント", opportunity: "機会", payment: "支払い", technical: "技術的な問題", other: "その他", requests: "自分の依頼", replies: "依頼と返信", noReplies: "過去の依頼はありません。", response: "サポートチームの返信", pending: "返信待ち", open: "新規", inProgress: "対応中", resolved: "解決済み", closed: "終了" },
    review: { title: "機会の審査", description: "ユーザーが送信した機会を審査します。", pending: "審査待ちの機会はありません。", approve: "承認して公開", approvePublished: "変更を承認", reject: "却下", edit: "編集", save: "変更を保存", cancel: "キャンセル", translate: "現在の機会を翻訳", translating: "翻訳を作成中...", translated: "翻訳を作成しました", access: "審査する権限がありません。", error: "処理を完了できませんでした。" },
    supportTeam: { title: "サポートチーム", description: "チームメンバーと権限を管理します。", grant: "サポートに追加", revoke: "サポートから削除", admin: "管理者", opportunities: "機会を審査", reports: "報告を管理", requests: "サポート依頼を管理", access: "管理者のみ利用できます。", error: "アクセスを更新できませんでした。" },
    submit: { title: "機会を追加", description: "公開前に審査する詳細を送信します。", name: "名前", shortDescription: "短い説明", details: "詳細", link: "リンク", earnings: "予想収益", category: "カテゴリ", categoryPlaceholder: "入力して検索し、カテゴリを選択してください", categoryRequired: "リストからカテゴリを選択してください。", countries: "利用可能な国", devices: "対応端末", paymentMethods: "支払い方法", requirements: "要件", optional: "任意、カンマで区切ってください", submit: "審査に送信", cancel: "機会に戻る", loginRequired: "機会を追加するにはログインしてください。", invalidUrl: "http:// または https:// で始まるURLを入力してください。", success: "審査に送信しました。", error: "送信できませんでした。", aiTitle: "外部リンクをAIで分析", aiBadge: "AI", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "リンクを分析", aiAnalyzing: "分析中...", aiMissingUrl: "先に外部リンクを入力してください。", aiInvalidUrl: "httpまたはhttpsで始まる有効なリンクを入力してください。", aiError: "リンクを分析できませんでした。別のリンクを試してください。", aiDuplicate: "この機会はすでに審査待ち、または公開されています。", aiSuccess: "リンクを分析し、確認用にデータを追加しました。" },
  },
  zh: {
    forgot: { title: "忘记密码", subtitle: "输入邮箱，我们会发送重置密码的链接。", email: "电子邮箱", send: "发送重置链接", sending: "发送中...", back: "返回登录", success: "密码重置链接已发送。", error: "无法发送重置链接。" },
    reset: { title: "重置密码", password: "新密码", confirm: "确认密码", save: "保存密码", saving: "保存中...", back: "返回登录", success: "密码已更新。", error: "无法更新密码。" },
    support: { title: "支持与帮助", subtitle: "提交问题后，支持团队会跟进。", email: "电子邮箱", type: "问题类型", description: "问题描述", submit: "发送支持请求", newRequest: "提交请求", success: "支持请求已发送。", error: "无法发送支持请求。", account: "账户", opportunity: "机会", payment: "支付", technical: "技术问题", other: "其他", requests: "我的请求", replies: "我的请求和回复", noReplies: "暂无历史请求。", response: "支持团队回复", pending: "尚未回复", open: "新建", inProgress: "处理中", resolved: "已解决", closed: "已关闭" },
    review: { title: "审核机会", description: "审核用户提交的机会。", pending: "暂无待审核机会。", approve: "批准并发布", approvePublished: "批准更改", reject: "拒绝", edit: "编辑", save: "保存更改", cancel: "取消", translate: "翻译当前机会", translating: "正在创建翻译...", translated: "翻译已创建", access: "你没有审核权限。", error: "操作无法完成。" },
    supportTeam: { title: "支持团队", description: "管理支持团队成员和权限。", grant: "加入支持团队", revoke: "移出支持团队", admin: "管理员", opportunities: "审核机会", reports: "管理举报", requests: "管理支持请求", access: "仅管理员可访问。", error: "无法更新权限。" },
    submit: { title: "添加机会", description: "提交机会详情，审核通过后才会发布。", name: "名称", shortDescription: "简短描述", details: "详细信息", link: "链接", earnings: "预期收益", category: "分类", categoryPlaceholder: "输入搜索，然后选择分类", categoryRequired: "请从列表中选择一个分类。", countries: "可用国家", devices: "支持设备", paymentMethods: "支付方式", requirements: "要求", optional: "可选，请用逗号分隔", submit: "提交审核", cancel: "返回机会", loginRequired: "请登录后添加机会。", invalidUrl: "请输入以 http:// 或 https:// 开头的有效网址。", success: "机会已提交审核。", error: "无法提交机会。", aiTitle: "使用 AI 分析外部链接", aiBadge: "AI", aiPlaceholder: "https://example.com/opportunity", aiAnalyze: "分析链接", aiAnalyzing: "正在分析...", aiMissingUrl: "请先输入外部链接。", aiInvalidUrl: "请输入以 http 或 https 开头的有效链接。", aiError: "无法分析链接，请尝试其他链接。", aiDuplicate: "此机会已在审核队列中或已经发布。", aiSuccess: "链接已分析，数据已添加到表单供审核。" },
  },
} satisfies Record<LanguageCode, PageCopy>;

export function getPageCopy(language: LanguageCode) {
  return pageCopy[language];
}
