alter table public.support_permissions
  add column if not exists can_manage_support_requests boolean not null default false;

create table if not exists public.support_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  issue_type text not null check (issue_type in ('account', 'opportunity', 'payment', 'technical', 'other')),
  description text not null,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  handled_by uuid references auth.users(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.support_requests enable row level security;

create policy "Users can view their own support requests"
  on public.support_requests for select to authenticated
  using (user_id = auth.uid() or public.has_support_permission('manage_support_requests'));

create or replace function public.has_support_permission(p_permission text)
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select public.is_opportunity_admin()
    or exists (
      select 1
      from public.user_roles roles
      join public.support_permissions permissions on permissions.user_id = roles.user_id
      where roles.user_id = auth.uid()
        and roles.role = 'support'
        and (
          (p_permission = 'review_opportunities' and permissions.can_review_opportunities)
          or (p_permission = 'manage_reports' and permissions.can_manage_reports)
          or (p_permission = 'manage_support_requests' and permissions.can_manage_support_requests)
        )
    );
$$;

create or replace function public.create_support_request(
  p_email text,
  p_issue_type text,
  p_description text
)
returns bigint
language plpgsql
security definer set search_path = public
as $$
declare
  request_id bigint;
begin
  if coalesce(trim(p_email), '') = ''
    or coalesce(trim(p_description), '') = '' then
    raise exception 'Email and description are required';
  end if;

  if p_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'A valid email address is required';
  end if;

  if p_issue_type not in ('account', 'opportunity', 'payment', 'technical', 'other') then
    raise exception 'Invalid issue type';
  end if;

  insert into public.support_requests (user_id, email, issue_type, description)
  values (auth.uid(), lower(trim(p_email)), p_issue_type, trim(p_description))
  returning id into request_id;

  return request_id;
end;
$$;

create or replace function public.update_support_request_status(
  p_request_id bigint,
  p_status text
)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.has_support_permission('manage_support_requests') then
    raise exception 'Support request management access is required';
  end if;

  if p_status not in ('open', 'in_progress', 'resolved', 'closed') then
    raise exception 'Invalid support request status';
  end if;

  update public.support_requests
  set status = p_status,
      handled_by = auth.uid(),
      handled_at = now(),
      updated_at = now()
  where id = p_request_id;

  if not found then
    raise exception 'Support request not found';
  end if;
end;
$$;

create or replace function public.set_support_permission(
  p_user_id uuid,
  p_permission text,
  p_enabled boolean
)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_opportunity_admin() then
    raise exception 'Administrator access is required';
  end if;

  if p_permission not in ('review_opportunities', 'manage_reports', 'manage_support_requests') then
    raise exception 'Invalid support permission';
  end if;

  if not exists (
    select 1 from public.user_roles
    where user_id = p_user_id and role = 'support'
  ) then
    raise exception 'The user is not a support-team member';
  end if;

  insert into public.support_permissions (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  if p_permission = 'review_opportunities' then
    update public.support_permissions set can_review_opportunities = p_enabled, updated_at = now() where user_id = p_user_id;
  elsif p_permission = 'manage_reports' then
    update public.support_permissions set can_manage_reports = p_enabled, updated_at = now() where user_id = p_user_id;
  else
    update public.support_permissions set can_manage_support_requests = p_enabled, updated_at = now() where user_id = p_user_id;
  end if;
end;
$$;

grant execute on function public.create_support_request(text, text, text) to anon, authenticated;
grant execute on function public.update_support_request_status(bigint, text) to authenticated;
grant execute on function public.set_support_permission(uuid, text, boolean) to authenticated;
