create table if not exists public.opportunity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  event_type text not null default 'started',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.opportunity_events
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table public.opportunity_events
  drop constraint if exists opportunity_events_event_type_check;

alter table public.opportunity_events
  add constraint opportunity_events_event_type_check
  check (event_type = 'started') not valid;

alter table public.opportunity_events enable row level security;

create index if not exists opportunity_events_opportunity_id_idx
  on public.opportunity_events (opportunity_id);

create index if not exists opportunity_events_created_at_idx
  on public.opportunity_events (created_at desc);

drop policy if exists "Users can insert their opportunity events" on public.opportunity_events;
drop policy if exists "Admins can view opportunity events" on public.opportunity_events;

create policy "Users can insert their opportunity events"
  on public.opportunity_events for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Admins can view opportunity events"
  on public.opportunity_events for select
  to authenticated
  using (public.is_opportunity_admin());
