create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  report_type text not null default 'other',
  message text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint reports_status_check check (status in ('pending', 'reviewed', 'resolved', 'rejected'))
);

alter table public.reports enable row level security;

create policy "Users can view their own reports"
  on public.reports for select to authenticated
  using (user_id = auth.uid() or public.has_opportunity_review_access());

create or replace function public.create_report(
  p_opportunity_id bigint,
  p_report_type text default 'other',
  p_message text default null
)
returns bigint
language plpgsql
security definer set search_path = public
as $$
declare
  report_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required';
  end if;

  if not exists (
    select 1 from public.opportunities
    where id = p_opportunity_id and status = 'published'
  ) then
    raise exception 'The opportunity was not found';
  end if;

  if exists (
    select 1 from public.reports
    where user_id = auth.uid() and opportunity_id = p_opportunity_id
  ) then
    raise exception 'You have already reported this opportunity';
  end if;

  insert into public.reports (user_id, opportunity_id, report_type, message)
  values (auth.uid(), p_opportunity_id, coalesce(nullif(trim(p_report_type), ''), 'other'), nullif(trim(p_message), ''))
  returning id into report_id;

  return report_id;
end;
$$;

grant execute on function public.create_report(bigint, text, text) to authenticated;
